version: "2"
services:
  nodejs:
    build: ./nodejs
    environment:
      MONGODB: 'mongodb://mongodb:27017/tenx'
    volumes:
      - ./nodejs/src:/usr/src/app/src
    ports:
      - "3000:3000"
    networks:
      - my-net
  java:
    build: ./java
    command: sh -c "mvn package && java -jar target/gs-spring-boot-docker-0.1.0.jar"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGODB: 'mongodb://mongodb:27017/tenx'
    volumes:
      - ./java:/usr/src/app
    ports:
      - "8080:8080"
    networks:
      - my-net
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    networks:
      - my-net
networks:
  my-net:
    driver: bridge
